In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

# Cross-Validation and Bias-Variance decomposition
## Cross-Validation
Implementing 4-fold cross-validation below:

In [2]:
from helpers import load_data

# load dataset
x, y = load_data()

In [4]:
#fonctions from lab 3

def least_squares(y, tx):
    """calculate the least squares solution."""
    # least squares: TODO
    # returns mse, and optimal weights
    
    gram=(tx.T).dot(tx)
    w = (np.linalg.inv(gram).dot(tx.T)).dot(y)
    N = y.shape[0]
    e = y-tx.dot(w)
    MSE = 1/(2*N) * (e.T).dot(e)
    
    return MSE, w 

import math

def split_data(x, y, ratio, seed=1):
    """
    split the dataset based on the split ratio. If ratio is 0.8 
    you will have 80% of your data set dedicated to training 
    and the rest dedicated to testing
    """
    # set seed
    np.random.seed(seed)
    num_row = y.shape[0]
    y_random=np.zeros(num_row)
    x_random=np.zeros(num_row)
    # split the data based on the given ratio
    indices = np.random.permutation(num_row)
    for i in range(len(indices)): 
        y_random[i]=y[indices[i]]
        x_random[i]=x[indices[i]]
    sep_row = math.floor(ratio * num_row)
    y_tr = y_random[:sep_row]
    x_tr = x_random[:sep_row]
    y_te = y_random[sep_row:]
    x_te = x_random[sep_row:]
    
    return y_tr, x_tr, y_te, x_te

def ridge_regression(y, tx, lambda_):
    """implement ridge regression."""

    # ridge regression: TODO
    N=2*tx.shape[0]
    XTX=np.dot(tx.T,tx)
    lambda_I= (lambda_*N)*np.identity(tx.shape[1])
    XTY= np.dot(tx.T,y)
    
    w_ridge = np.linalg.solve(XTX+lambda_I,XTY)
    err = y - tx.dot(w_ridge)
    
    return compute_loss_l(err,mse), w_ridge

In [5]:
def build_k_indices(y, k_fold, seed):
    """build k indices for k-fold."""
    num_row = y.shape[0]
    interval = int(num_row / k_fold)
    np.random.seed(seed)
    indices = np.random.permutation(num_row)
    k_indices = [indices[k * interval: (k + 1) * interval]
                 for k in range(k_fold)]
    return np.array(k_indices)

In [16]:
k_fold = 5
seed = 1
k=2
ind = build_k_indices(x, k_fold, seed)
print(ind)
ind[k:]
y[ind[:k]]

[[27 35 40 38  2  3 48 29 46 31]
 [32 39 21 36 19 42 49 26 22 13]
 [41 17 45 24 23  4 33 14 30 10]
 [28 44 34 18 20 25  6  7 47  1]
 [16  0 15  5 11  9  8 12 43 37]]


array([[-0.56851939, -0.15050841,  0.66750938, -1.30763072,  1.28930361,
        -0.26815701,  0.12187968,  0.99490902, -0.76646743,  0.72778149],
       [ 0.77328884, -0.82651893,  0.95121182,  0.25252451, -0.37259529,
         0.07691219, -1.04670162, -0.55991146,  0.60599855,  0.03761024]])

In [28]:
from costs import compute_mse
from ridge_regression import ridge_regression
from build_polynomial import build_poly

def cross_validation(y, x, k_indices, k, lambda_, degree):
    """return the loss of ridge regression."""

    # get k'th subgroup in test, others in train: TODO
    indices = build_k_indices(y, k_fold, seed)
    y_tr = y[indices[:k]]
    y_te = y[indices[k:]]
    indices = build_k_indices(x, k_fold, seed)
    x_tr = x[indices[:k]]
    x_te = x[indices[k:]]
    
    # ***************************************************
    # form data with polynomial degree: TODO
    x_tr = build_poly(x_tr,  degree)
    x_te = build_poly(x_te,  degree)
    
    # ***************************************************
    # ridge regression: TODO
     # calculate the loss for train and test data: TODO
    loss_tr, w_tr = ridge_regression(y_tr, tx_tr, lambda_)
    loss_te, w_te = ridge_regression(y_te, tx_te, lambda_)
        
    return loss_tr, loss_te

In [29]:
from plots import cross_validation_visualization

def cross_validation_demo():
    seed = 1
    degree = 7
    k_fold = 4
    lambdas = np.logspace(-4, 0, 30)
    # split data in k fold
    k_indices = build_k_indices(y, k_fold, seed)
    # define lists to store the loss of training data and test data
    rmse_tr = []
    rmse_te = []

    # cross validation: TODO
    for lambda_ in lambdas:
        loss_tr, loss_te = cross_validation(y, x, k_indices, k, lambda_, degree)
    
    cross_validation_visualization(lambdas, rmse_tr, rmse_te)

In [30]:
cross_validation_demo()

NotImplementedError: 

## Bias-Variance Decomposition
Visualize bias-variance trade-off by implementing the function `bias_variance_demo()` below:

In [ ]:
from least_squares import least_squares
from split_data import split_data
from plots import bias_variance_decomposition_visualization

def bias_variance_demo():
    """The entry."""
    # define parameters
    seeds = range(100)
    num_data = 10000
    ratio_train = 0.005
    degrees = range(1, 10)
    
    # define list to store the variable
    rmse_tr = np.empty((len(seeds), len(degrees)))
    rmse_te = np.empty((len(seeds), len(degrees)))
    
    for index_seed, seed in enumerate(seeds):
        np.random.seed(seed)
        x = np.linspace(0.1, 2 * np.pi, num_data)
        y = np.sin(x) + 0.3 * np.random.randn(num_data).T
        # ***************************************************
        # INSERT YOUR CODE HERE
        # split data with a specific seed: TODO
        # ***************************************************
        raise NotImplementedError
        # ***************************************************
        # INSERT YOUR CODE HERE
        # bias_variance_decomposition: TODO
        # ***************************************************
        raise NotImplementedError

    bias_variance_decomposition_visualization(degrees, rmse_tr, rmse_te)

bias_variance_demo()